### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bfbca** [bbottema/gulp-js-base64-inject#1]
Hi, thank you for a useful gulp plugin.
There is a bug. This line:
```
var filecontents = mime.lookup(filepath) + ';base64,' + fs.readFileSync(filepath).toString('base64');
```
should read like this:
```
var filecontents = mime.lookup(filepath) + ';base64,' + fs.readFileSync(fp).toString('base64');
```
Otherwise fs.readFileSync() errors out with "unable to read utf8 file".

**Comment by bbottema** [comment]
Done. Available under 1.0.1. Thanks for reporting!
